<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="YolandeH-Dell2" failures="2" tests="6" name="Test - practical on Listeners" time="0.084" errors="0" timestamp="2022-03-30T17:29:16 SAST">
  <testcase classname="practicalListeners.PracTestListeners" name="skippedTest1" time="0.009">
    <skipped/>
  </testcase> <!-- skippedTest1 -->
  <testcase classname="practicalListeners.PracTestListeners" name="skippedTest2" time="0.002">
    <skipped/>
  </testcase> <!-- skippedTest2 -->
  <testcase classname="practicalListeners.PracTestListeners" name="testFails1" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at practicalListeners.PracTestListeners.testFails1(PracTestListeners.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testFails1 -->
  <testcase classname="practicalListeners.PracTestListeners" name="testFails2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at practicalListeners.PracTestListeners.testFails2(PracTestListeners.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testFails2 -->
  <testcase classname="practicalListeners.PracTestListeners" name="testPasses1" time="0.001"/>
  <testcase classname="practicalListeners.PracTestListeners" name="testPasses2" time="0.002"/>
</testsuite> <!-- Test - practical on Listeners -->
